import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './(LayoutComponents)/Navbar'
import Footer from './(LayoutComponents)/Footer'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto`}>
        <Navbar />
        <div className="mx-auto w-[80%]">

          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
